# Generated by Django 3.2.2 on 2021-05-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_age'),
        ('single', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
    ]
